### ISSUE TITLE
Updates on Message Frequency

### ISSUE THREAD

**Issue by mr-chris** [cweems/twilio-keyword#1]
Often times customers get caught up on message frequency believing they need to stick with a rigid template like the one we provided here, while wishing they had some more freedom to customize the language without realizing they absolutely can.

Minimum Lovable
- Users should be able to indicate that "Message frequency may vary." Message frequency is not always predictable, but as long as people signing up are aware of that it is acceptable. 
- Users should be able to edit the Interval to add their own, depending on their use case.

Most Lovable
- Give users freedom to modify the verbiage while still remaining complaint. "_You will receive one message per volunteer opportunity, but no more than four messages per month._" This language is much more descriptive and potentially more accurate to the reality of the campaign.

**Comment by cweems** [comment]
@mr-chris I think I've gotten this to most-lovable with this PR: https://github.com/cweems/twilio-keyword/pull/3

Is there any chance you could take a look and provide any copy / UX feedback?
